Repository cerner/terra-clinical, pull requests merged in 2018-05, with the labels that each got.

#330 Update stylelint dependencies
  package.json
Labels: build-tools

#315 Enable parallel testing during builds
  .dockerignore
  .travis.yml
  Dockerfile
  package.json
  packages/terra-clinical-onset-picker/.npmrc
  wdio.conf.js
Labels: build-tools, enhancement, monorepo, testing

#339 Update root stylelint check
  package.json
Labels: build-tools, sync with terra-core
