Repository cerner/terra-clinical, pull requests merged in 2018-02, with the labels that each got.

#268 Enable Install As Package Setup
  package.json
  packages/terra-clinical-action-header/.npmignore
  packages/terra-clinical-application-site/.npmignore
  packages/terra-clinical-application/.npmignore
  packages/terra-clinical-detail-view/.npmignore
  packages/terra-clinical-error-view/.npmignore
  packages/terra-clinical-header/.npmignore
  packages/terra-clinical-item-collection/.npmignore
  packages/terra-clinical-item-display/.npmignore
  packages/terra-clinical-item-view/.npmignore
  packages/terra-clinical-label-value-view/.npmignore
  packages/terra-clinical-no-data-view/.npmignore
  packages/terra-clinical-onset-picker/.npmignore
  packages/terra-clinical-site/.npmignore
  scripts/post-install/index.js
Labels: monorepo

#273 Add option to display close button on small viewports
  CONTRIBUTORS.md
  packages/terra-clinical-action-header/CHANGELOG.md
  packages/terra-clinical-action-header/src/ActionHeader.jsx
  packages/terra-clinical-action-header/tests/jest/__snapshots__/ActionHeader.test.jsx.snap
  packages/terra-clinical-action-header/tests/nightwatch/ActionHeaderTestRoutes.jsx
  packages/terra-clinical-action-header/tests/nightwatch/ActionHeaderTests.jsx
  packages/terra-clinical-action-header/tests/nightwatch/KeepCloseButtonActionHeader.jsx
  packages/terra-clinical-action-header/tests/nightwatch/action-header-spec.js
  packages/terra-clinical-site/src/examples/action-header/ActionHeader-KeepClose.jsx
  packages/terra-clinical-site/src/examples/action-header/Index.jsx
Labels: action-header, enhancement

#281 Disable cache for travis-ci build
  .travis.yml
Labels: Small
