Repository cerner/terra-clinical, pull requests merged in 2018-11, with the labels that each got.

#421 Revert Tar Archive files
  dangerfile.js
  packages/terra-clinical-application/.npmignore
  packages/terra-clinical-application/package.json
  packages/terra-clinical-application/terra-clinical-application.tgz
  packages/terra-clinical-data-grid/.npmignore
  packages/terra-clinical-data-grid/package.json
  packages/terra-clinical-data-grid/terra-clinical-data-grid.tgz
  packages/terra-clinical-detail-view/.npmignore
  packages/terra-clinical-detail-view/package.json
  packages/terra-clinical-detail-view/terra-clinical-detail-view.tgz
  packages/terra-clinical-header/.npmignore
  packages/terra-clinical-header/package.json
  packages/terra-clinical-header/terra-clinical-header.tgz
  packages/terra-clinical-item-collection/.npmignore
  packages/terra-clinical-item-collection/package.json
  packages/terra-clinical-item-collection/terra-clinical-item-collection.tgz
  packages/terra-clinical-item-display/.npmignore
  packages/terra-clinical-item-display/package.json
  packages/terra-clinical-item-display/terra-clinical-item-display.tgz
  packages/terra-clinical-item-view/.npmignore
  packages/terra-clinical-item-view/package.json
  packages/terra-clinical-item-view/terra-clinical-item-view.tgz
  packages/terra-clinical-label-value-view/.npmignore
  packages/terra-clinical-label-value-view/package.json
  packages/terra-clinical-label-value-view/terra-clinical-label-value-view.tgz
  packages/terra-clinical-onset-picker/.npmignore
  packages/terra-clinical-onset-picker/package.json
  packages/terra-clinical-onset-picker/terra-clinical-onset-picker.tgz
Labels: tech-only

#419 [terra-clinical-data-grid] Adding checkmarks to row selection columns
  README.md
  packages/terra-clinical-data-grid/CHANGELOG.md
  packages/terra-clinical-data-grid/package.json
  packages/terra-clinical-data-grid/src/DataGrid.jsx
  packages/terra-clinical-data-grid/src/subcomponents/RowSelectionCell.jsx
  packages/terra-clinical-data-grid/src/subcomponents/RowSelectionCell.module.scss
  packages/terra-clinical-data-grid/src/utils/dataGridUtils.js
  packages/terra-clinical-data-grid/tests/jest/__snapshots__/DataGrid.test.jsx.snap
  packages/terra-clinical-data-grid/tests/jest/subcomponents/RowSelectionCell.test.jsx
  packages/terra-clinical-data-grid/tests/jest/subcomponents/__snapshots__/RowSelectionCell.test.jsx.snap
  packages/terra-clinical-data-grid/tests/jest/utils/dataGridUtils.test.js
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_cell_selection_hover[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_cell_selection_hover[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_cell_selections[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_cell_selections[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_column_header_selections[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_column_header_selections[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_row_selection_hover[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_row_selection_hover[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_row_selections[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_row_selections[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_selected_row_hover[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_selected_row_hover[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_tabbing[#backward-headers].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_tabbing[#backward-sections].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_tabbing[#forward-headers].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_huge/data-grid-spec/with_tabbing[#forward-sections].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_cell_selection_hover[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_cell_selection_hover[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_cell_selections[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_cell_selections[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_column_header_selections[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_column_header_selections[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_row_selection_hover[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_row_selection_hover[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_row_selections[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_row_selections[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_selected_row_hover[default].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_selected_row_hover[themed].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_tabbing[#backward-headers].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_tabbing[#backward-sections].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_tabbing[#forward-headers].png
  packages/terra-clinical-data-grid/tests/wdio/__snapshots__/reference/en/chrome_medium/data-grid-spec/with_tabbing[#forward-sections].png
  packages/terra-clinical-data-grid/tests/wdio/data-grid-spec.js
Labels: data-grid

#425 Fail on Danger or Lint
  .travis.yml
Labels: build-tools, testing
