Repository cerner/terra-clinical, pull requests merged in 2019-06, with the labels that each got.

#512 Dangerfile changelog checking improvements
  dangerfile.js
  package.json
Labels: build-tools

#519 Update devDependencies
  package.json
Labels: dependency-update, tech-only

#518 [terra-clinical] Removed node_modules from .npmignore
  packages/terra-clinical-application/.npmignore
  packages/terra-clinical-application/CHANGELOG.md
  packages/terra-clinical-data-grid/.npmignore
  packages/terra-clinical-data-grid/CHANGELOG.md
  packages/terra-clinical-detail-view/.npmignore
  packages/terra-clinical-detail-view/CHANGELOG.md
  packages/terra-clinical-header/.npmignore
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-item-collection/.npmignore
  packages/terra-clinical-item-collection/CHANGELOG.md
  packages/terra-clinical-item-display/.npmignore
  packages/terra-clinical-item-display/CHANGELOG.md
  packages/terra-clinical-item-view/.npmignore
  packages/terra-clinical-item-view/CHANGELOG.md
  packages/terra-clinical-label-value-view/.npmignore
  packages/terra-clinical-label-value-view/CHANGELOG.md
  packages/terra-clinical-onset-picker/.npmignore
  packages/terra-clinical-onset-picker/CHANGELOG.md
Labels: build-tools, tech-only

#520 Update to use Terra.describeViewports
  packages/terra-clinical-application/CHANGELOG.md
  packages/terra-clinical-application/tests/wdio/application-spec.js
  packages/terra-clinical-data-grid/CHANGELOG.md
  packages/terra-clinical-data-grid/tests/wdio/data-grid-spec.js
  packages/terra-clinical-detail-view/CHANGELOG.md
  packages/terra-clinical-detail-view/tests/wdio/DetailList/detail-list-spec.js
  packages/terra-clinical-detail-view/tests/wdio/DetailListItem/detail-list-item-spec.js
  packages/terra-clinical-detail-view/tests/wdio/DetailView/detail-view-spec.js
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/tests/wdio/header-spec.js
  packages/terra-clinical-item-collection/CHANGELOG.md
  packages/terra-clinical-item-collection/tests/wdio/clinical-item-collection-spec.js
  packages/terra-clinical-item-display/CHANGELOG.md
  packages/terra-clinical-item-display/tests/wdio/item-display-spec.js
  packages/terra-clinical-item-view/CHANGELOG.md
  packages/terra-clinical-item-view/tests/wdio/item-view-spec.js
  packages/terra-clinical-label-value-view/CHANGELOG.md
  packages/terra-clinical-label-value-view/tests/wdio/label-value-view-spec.js
  packages/terra-clinical-onset-picker/CHANGELOG.md
  packages/terra-clinical-onset-picker/tests/wdio/onset-spec.js
Labels: tech-only, testing

#510 Add enumerations for PropTypes.oneOf usage
  packages/terra-clinical-application/CHANGELOG.md
  packages/terra-clinical-data-grid/CHANGELOG.md
  packages/terra-clinical-data-grid/src/DataGrid.jsx
  packages/terra-clinical-data-grid/src/proptypes/columnDataShape.js
  packages/terra-clinical-data-grid/src/subcomponents/HeaderCell.jsx
  packages/terra-clinical-item-collection/CHANGELOG.md
  packages/terra-clinical-item-collection/src/Item.jsx
  packages/terra-clinical-item-collection/src/ItemCollection.jsx
  packages/terra-clinical-item-display/CHANGELOG.md
  packages/terra-clinical-item-display/src/ItemDisplay.jsx
  packages/terra-clinical-item-view/CHANGELOG.md
  packages/terra-clinical-item-view/src/ItemView.jsx
  packages/terra-clinical-onset-picker/CHANGELOG.md
  packages/terra-clinical-onset-picker/src/OnsetPicker.jsx
  packages/terra-clinical-onset-picker/tests/jest/__snapshots__/OnsetPicker.test.jsx.snap
Labels: data-grid, item-collection, item-display, item-view, onset-picker, tech-only
