Repository cerner/terra-clinical, pull requests merged in 2019-05, with the labels that each got.

#493 Terra site update
  CONTRIBUTORS.md
  package.json
Labels: build-tools

#482 [terra-clinical-header] Increase rule specificity for the collapsible child element.
  CONTRIBUTORS.md
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/src/Header.scss
Labels: bug-fix, header, tech-only

#503 FIxes issue #501 updated typo bug
  packages/terra-clinical-item-view/README.md
Labels: docs

#504 Fixes issue #500 corrected client to clinical
  packages/terra-clinical-item-display/README.md
Labels: docs, item-display

#497 StyleLintConfig and StyleLint package version updated to ^3.0.0 and ^10.0.1
  CONTRIBUTORS.md
  package.json
Labels: build-tools, tech-only

#499 [Onset-Picker] Update doc for violation scenarios.
  packages/terra-clinical-onset-picker/CHANGELOG.md
  packages/terra-clinical-onset-picker/docs/README.md
  packages/terra-clinical-onset-picker/src/terra-dev-site/doc/example/DefaultOnset.jsx
  packages/terra-clinical-onset-picker/src/terra-dev-site/doc/example/HandledOnset.jsx
Labels: bug-fix, docs, onset-picker, site

#511 Update badges to point to travis-ci.com
  .travis.yml
  README.md
  packages/terra-clinical-application/README.md
  packages/terra-clinical-data-grid/README.md
  packages/terra-clinical-detail-view/README.md
  packages/terra-clinical-header/README.md
  packages/terra-clinical-item-collection/README.md
  packages/terra-clinical-item-display/README.md
  packages/terra-clinical-item-view/README.md
  packages/terra-clinical-label-value-view/README.md
  packages/terra-clinical-onset-picker/README.md
Labels: docs
