Repository cerner/terra-clinical, pull requests merged in 2019-01, with the labels that each got.

#436 Improve site accessibility
  README.md
  packages/terra-clinical-item-collection/CHANGELOG.md
  packages/terra-clinical-item-collection/docs/README.md
Labels: accessibility, item-collection

#438 Update Wdio Timeout Values
  packages/terra-clinical-item-collection/CHANGELOG.md
  packages/terra-clinical-item-collection/tests/wdio/clinical-item-collection-spec.js
Labels: tech-only, testing

#444 Changelog Dev Site Doc Pages
  packages/terra-clinical-application/CHANGELOG.md
  packages/terra-clinical-application/src/terra-dev-site/doc/clinical-application/ChangeLog.2.doc.jsx
  packages/terra-clinical-application/src/terra-dev-site/doc/clinical-application/clinicalApplication.1.doc.jsx
  packages/terra-clinical-data-grid/CHANGELOG.md
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/ChangeLog.3.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/ContentCellLayout.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/ContentCellLayout.scss
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/CustomHeaderCellLayout.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/CustomHeaderCellLayout.scss
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/Datagrid.1.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/Datagrid.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithColumnResizing.5.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithColumnResizing.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithCustomContent.7.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithCustomContent.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithNoPinnedColumns.2.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithNoPinnedColumns.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithPaging.6.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithPaging.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithSelections.4.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithSelections.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithSubsections.3.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithSubsections.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithoutFill.8.doc.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/DatagridExamples.2/DatagridWithoutFill.jsx
  packages/terra-clinical-data-grid/src/terra-dev-site/doc/clinical-data-grid/clinicalDataGrid.1.doc.jsx
  packages/terra-clinical-detail-view/CHANGELOG.md
  packages/terra-clinical-detail-view/src/terra-dev-site/doc/clinical-detail-view/ChangeLog.2.doc.jsx
  packages/terra-clinical-detail-view/src/terra-dev-site/doc/clinical-detail-view/clinicalDetailView.1.doc.jsx
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/src/terra-dev-site/doc/clinical-header/ChangeLog.2.doc.jsx
  packages/terra-clinical-header/src/terra-dev-site/doc/clinical-header/clinicalHeader.1.doc.jsx
  packages/terra-clinical-item-collection/CHANGELOG.md
  packages/terra-clinical-item-collection/src/terra-dev-site/doc/clinical-item-collection/ChangeLog.2.doc.jsx
  packages/terra-clinical-item-collection/src/terra-dev-site/doc/clinical-item-collection/clinicalItemCollection.1.doc.jsx
  packages/terra-clinical-item-display/CHANGELOG.md
  packages/terra-clinical-item-display/src/terra-dev-site/doc/clinical-item-display/ChangeLog.2.doc.jsx
  packages/terra-clinical-item-display/src/terra-dev-site/doc/clinical-item-display/clinicalItemDisplay.1.doc.jsx
  packages/terra-clinical-item-view/CHANGELOG.md
  packages/terra-clinical-item-view/src/terra-dev-site/doc/clinical-item-view/ChangeLog.2.doc.jsx
  packages/terra-clinical-item-view/src/terra-dev-site/doc/clinical-item-view/clinicalItemView.1.doc.jsx
  packages/terra-clinical-label-value-view/CHANGELOG.md
  packages/terra-clinical-label-value-view/src/terra-dev-site/doc/clinical-label-value-view/ChangeLog.2.doc.jsx
  packages/terra-clinical-label-value-view/src/terra-dev-site/doc/clinical-label-value-view/clinicalLabelValueView.1.doc.jsx
  packages/terra-clinical-onset-picker/CHANGELOG.md
  packages/terra-clinical-onset-picker/src/terra-dev-site/doc/clinical-onset-picker/ChangeLog.2.doc.jsx
  packages/terra-clinical-onset-picker/src/terra-dev-site/doc/clinical-onset-picker/ClinicalOnsetPicker.1.doc.jsx
Labels: docs

#451 Add .npmignore to Package
  packages/terra-clinical-application/.npmignore
  packages/terra-clinical-data-grid/.npmignore
  packages/terra-clinical-detail-view/.npmignore
  packages/terra-clinical-header/.npmignore
  packages/terra-clinical-item-collection/.npmignore
  packages/terra-clinical-item-display/.npmignore
  packages/terra-clinical-item-view/.npmignore
  packages/terra-clinical-label-value-view/.npmignore
  packages/terra-clinical-onset-picker/.npmignore
Labels: build-tools, tech-only

#450 Update Broken Onset Picker Tests
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_month_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_month_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_year_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_year_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_months_duration_if_age_is_less_than_a_month_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_years_duration_if_age_is_less_than_a_year_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_month_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_month_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_year_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_year_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_months_duration_if_age_is_less_than_a_month_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_years_duration_if_age_is_less_than_a_year_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_month_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_month_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_year_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_year_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_months_duration_if_age_is_less_than_a_month_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_years_duration_if_age_is_less_than_a_year_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/onset-spec.js
Labels: onset-picker, tech-only, testing

#452 Enable a docker dev environment
  Dockerfile
  docker-compose.yml
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Can_select_a_month_between_the_birthdate_and_current_date[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Can_select_a_year_between_the_birthdate_and_current_year[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_month_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_month_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_year_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_a_year_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_months_duration_if_age_is_less_than_a_month_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_number_of_months_that_exceede_age[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_number_of_weeks_that_exceede_age[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Cannot_select_years_duration_if_age_is_less_than_a_year_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Displays_age_inputs_when_Age_granularity_is_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Displays_date_input_when_Date_granularity_is_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Displays_month_and_year_selection_only_when_Month-Year_granularity_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_enormous/onset-spec/Displays_year_selection_only_when_Year_granularity_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Can_select_a_month_between_the_birthdate_and_current_date[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Can_select_a_year_between_the_birthdate_and_current_year[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_month_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_month_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_year_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_a_year_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_months_duration_if_age_is_less_than_a_month_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_number_of_months_that_exceede_age[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_number_of_weeks_that_exceede_age[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Cannot_select_years_duration_if_age_is_less_than_a_year_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Displays_age_inputs_when_Age_granularity_is_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Displays_date_input_when_Date_granularity_is_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Displays_month_and_year_selection_only_when_Month-Year_granularity_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_medium/onset-spec/Displays_year_selection_only_when_Year_granularity_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Can_select_a_month_between_the_birthdate_and_current_date[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Can_select_a_year_between_the_birthdate_and_current_year[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_month_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_month_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_year_before_the_birthdate[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_a_year_in_the_future[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_months_duration_if_age_is_less_than_a_month_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_number_of_months_that_exceede_age[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_number_of_weeks_that_exceede_age[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Cannot_select_years_duration_if_age_is_less_than_a_year_old[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Displays_age_inputs_when_Age_granularity_is_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Displays_date_input_when_Date_granularity_is_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Displays_month_and_year_selection_only_when_Month-Year_granularity_selected[default].png
  packages/terra-clinical-onset-picker/tests/wdio/__snapshots__/reference/en/chrome_tiny/onset-spec/Displays_year_selection_only_when_Year_granularity_selected[default].png
Labels: build-tools

#448 Changed All Component Terra-Core Dependency Versions
  packages/terra-clinical-application/package.json
  packages/terra-clinical-data-grid/package.json
  packages/terra-clinical-detail-view/package.json
  packages/terra-clinical-item-collection/package.json
  packages/terra-clinical-item-view/package.json
  packages/terra-clinical-label-value-view/package.json
  packages/terra-clinical-onset-picker/package.json
Labels: data-grid, dependency-update

#454 Repo Dependency / Script Changes
  package.json
  packages/terra-clinical-application/package.json
  packages/terra-clinical-data-grid/package.json
  packages/terra-clinical-detail-view/package.json
  packages/terra-clinical-header/package.json
  packages/terra-clinical-item-display/package.json
  packages/terra-clinical-item-view/package.json
  packages/terra-clinical-label-value-view/package.json
  packages/terra-clinical-onset-picker/package.json
  scripts/clean-modules/index.js
  scripts/post-install/index.js
Labels: build-tools
