Repository cerner/terra-clinical, pull requests merged in 2024-03, with the labels that each got.

#933 release-1-3-24
  packages/terra-clinical-data-grid/CHANGELOG.md
  packages/terra-clinical-data-grid/package.json
  packages/terra-clinical-detail-view/CHANGELOG.md
  packages/terra-clinical-detail-view/package.json
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/package.json
  packages/terra-clinical-item-display/CHANGELOG.md
  packages/terra-clinical-item-display/package.json
  packages/terra-clinical-item-view/CHANGELOG.md
  packages/terra-clinical-item-view/package.json
  packages/terra-clinical-label-value-view/CHANGELOG.md
  packages/terra-clinical-label-value-view/package.json
  packages/terra-clinical-onset-picker/CHANGELOG.md
  packages/terra-clinical-onset-picker/package.json
  packages/terra-clinical-result/CHANGELOG.md
  packages/terra-clinical-result/package.json
Labels: release

#934 [terra-clinical-item-view] Added contentWidth prop to allow custom width for items
  packages/terra-clinical-item-view/CHANGELOG.md
  packages/terra-clinical-item-view/src/ItemView.jsx
  packages/terra-clinical-item-view/src/terra-dev-site/test/clinical-item-view/ContentWidthItemView.test.jsx
  packages/terra-clinical-item-view/tests/jest/ItemView.test.jsx
  packages/terra-clinical-item-view/tests/jest/__snapshots__/ItemView.test.jsx.snap
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_enormous/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_huge/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_large/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_medium/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_small/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/clinical-lowlight-theme/en/chrome_tiny/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_enormous/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_huge/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_large/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_medium/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_small/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/orion-fusion-theme/en/chrome_tiny/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_enormous/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_huge/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_large/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_medium/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_small/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/__snapshots__/reference/terra-default-theme/en/chrome_tiny/item-view-spec/with_custom_content_width.png
  packages/terra-clinical-item-view/tests/wdio/item-view-spec.js
  packages/terra-clinical-result/CHANGELOG.md
  packages/terra-clinical-result/translations/de.json
  packages/terra-clinical-result/translations/es-ES.json
  packages/terra-clinical-result/translations/es-US.json
  packages/terra-clinical-result/translations/es.json
  packages/terra-clinical-result/translations/nl-BE.json
  packages/terra-clinical-result/translations/nl.json
  packages/terra-clinical-result/translations/pt-BR.json
  packages/terra-clinical-result/translations/pt.json
Labels: :package: terra-clinical-item-view

#935 Release 06/03
  packages/terra-clinical-data-grid/CHANGELOG.md
  packages/terra-clinical-data-grid/package.json
  packages/terra-clinical-item-view/CHANGELOG.md
  packages/terra-clinical-item-view/package.json
  packages/terra-clinical-result/CHANGELOG.md
  packages/terra-clinical-result/package.json
Labels: release

#936 [terra-clinical-header] Wrapped start and end content
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/src/Header.jsx
  packages/terra-clinical-header/src/Header.module.scss
  packages/terra-clinical-header/tests/jest/Header.test.jsx
  packages/terra-clinical-header/tests/jest/__snapshots__/Header.test.jsx.snap
Labels: :package: terra-clinical-header

#937 Release 21/3
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/package.json
Labels: release

#938 [terra-clinical-header] Changed flex direction from column to row
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/src/Header.module.scss
Labels: :package: terra-clinical-header

#939 Release 26/3
  packages/terra-clinical-header/CHANGELOG.md
  packages/terra-clinical-header/package.json
Labels: release
